### ISSUE TITLE
スマホとPCでのメインビジュアル部分の変更

### ISSUE THREAD

**Issue by t-shimaoka** [yuzoiwasaki/besidethemusic-nuxt#4]
スマホで見た際のメインビジュアル部分が少し気になったのでCSSと画像を少し変更して添付のような見せ方はどうかなと思いました！合わせてPCでのメインヴィジュアル部分の見せ方も少し変えています ※背景画像自体も文字を入れたりと少し変更しました

SoucetreeからブランチをPUSHしてみたのですが接続できず＞＜

![SP](https://user-images.githubusercontent.com/4471460/82120387-95be1980-97c0-11ea-9235-2a3d65fc0773.jpg)
![PC](https://user-images.githubusercontent.com/4471460/82120391-9bb3fa80-97c0-11ea-8f9c-2f41b00b06e0.jpg)

@yuzoiwasaki

**Comment by yuzoiwasaki** [comment]
@t-shimaoka ありがとうございます！良いですね！こんな感じでプルリク送ってみていただけますでしょうか？
https://qiita.com/fuqda/items/a3e5270ff9cb4fbf31e2

**Comment by yuzoiwasaki** [comment]
以下のPRにて対応済みのためこちらはクローズします！ありがとうございました！
https://github.com/yuzoiwasaki/besidethemusic-nuxt/pull/5
